package com.example.onekids_project.common;

public interface AppSendSystemTitle {

    Long TEACHER_ATTENDACE_ARRIVE = 11L;
    Long TEACHER_ATTENDACE_ABSENT_YES = 12L;
    Long TEACHER_ATTENDACE_ABSENT_NO = 13L;

    Long TEACHER_ATTENDACE_LEAVE = 14L;

    Long PLUS_ATTENDACE_ARRIVE = 5L;
    Long PLUS_ATTENDACE_ABSENT_YES = 6L;
    Long PLUS_ATTENDACE_ABSENT_NO = 7L;

    Long PLUS_ATTENDACE_LEAVE = 8L;


    Long TEACHER_NOTIFY_TO_PARENT = 10L;

    Long PLUS_NOTIFY_TO_PARENT = 4L;

    Long PLUS_NOTIFY_TO_EMPLOYEE = 4L;

    Long TEACHER_BIRTHDAY_TO_PARENT = 9L;
    Long PLUS_BIRTHDAY_TO_KID = 9L;
    Long PLUS_BIRTHDAY_TO_PARENT = 9L;
    Long PLUS_BIRTHDAY_TO_TEACHER = 9L;


}
