package com.example.onekids_project.common;

public interface FirebaseSystemTitle {
    Long PARENT_MESSENGER = 22L;
    Long TEACHER_MESSENGER_CONFIM = 23L;
    Long PLUS_MESSENGER_CONFIM = 24L;
    Long TEACHER_MESSENGER_REPLY = 25L;

    Long PLUS_MESSENGER_REPLY = 26L;

    Long PARENT_MEDICINE = 27L;
    Long TEACHER_MEDICINE_CONFIM = 28L;
    Long TEACHER_MEDICINE_REPLY = 30L;
    Long PLUS_MEDICINE_CONFIM = 29L;
    Long PLUS_MEDICINE_REPLY = 31L;

    Long PARENT_ABSENT = 32L;
    Long TEACHER_ABSENT_CONFIM = 33L;
    Long TEACHER_ABSENT_REPLY = 35L;
    Long PLUS_ABSENT_CONFIM = 34L;
    Long PLUS_ABSENT_REPLY = 36L;

    Long PARENT_NOTIFY = 1L;
    Long TEACHER_NOTIFY = 2L;
    Long PLUS_NOTIFY = 3L;

    Long PARENT_BIRTHDAY = 1L;
    Long KID_BIRTHDAY = 1L;
    Long TEACHER_BIRTHDAY = 1L;
    Long PLUS_BIRTHDAY = 3L;

    Long PARENT_FEEDBACK = 54L;
    Long TEACHER_FEEDBACK = 57L;
    Long PLUS_FEEDBACK_CONFIM_PARENT = 55L;
    Long PLUS_FEEDBACK_CONFIM_TEACHER = 58L;
    Long PLUS_FEEDBACK_REPLY_PARENT = 56L;
    Long PLUS_FEEDBACK_REPLY_TEACHER = 59L;

    Long PARENT_ATTENDANCE = 1L;
    Long TEACHER_ATTENDANCE = 2L;
    Long PLUS_ATTENDANCE = 3L;

    Long PARENT_ALBUM = 37L;
    Long TEACHER_ALBUM = 37L;
    Long PLUS_ALBUM = 37L;

    Long TEACHER_ATTENDACE_ARRIVE = 11L;
    Long TEACHER_ATTENDACE_ABSENT_YES = 12L;
    Long TEACHER_ATTENDACE_ABSENT_NO = 13L;

    Long TEACHER_ATTENDACE_LEAVE = 14L;

    Long PLUS_ATTENDACE_ARRIVE = 5L;
    Long PLUS_ATTENDACE_ABSENT_YES = 6L;
    Long PLUS_ATTENDACE_ABSENT_NO = 7L;

    Long PLUS_ATTENDACE_LEAVE = 8L;

    Long PARENT_EVALUETE_DATE = 38L;
    Long PARENT_EVALUETE_REPLY_DATE = 39L;
    Long TEACHER_EVALUETE_REPLY_DATE = 40L;
    Long PLUS_EVALUETE_REPLY_DATE = 41L;

    Long PARENT_EVALUETE_WEEK = 42L;
    Long PARENT_EVALUETE_REPLY_WEEK = 43L;
    Long TEACHER_EVALUETE_REPLY_WEEK = 44L;
    Long PLUS_EVALUETE_REPLY_WEEK = 45L;

    Long PARENT_EVALUETE_MONTH = 46L;
    Long PARENT_EVALUETE_REPLY_MONTH = 47L;
    Long TEACHER_EVALUETE_REPLY_MONTH = 48L;
    Long PLUS_EVALUETE_REPLY_MONTH = 49L;

    Long PARENT_EVALUETE_PERIODIC = 50L;
    Long PARENT_EVALUETE_REPLY_PERIODIC = 51L;
    Long TEACHER_EVALUETE_REPLY_PERIODIC = 52L;
    Long PLUS_EVALUETE_REPLY_PERIODIC = 53L;


}
